# Social Media Bookmark Brain Builder Configuration
# Copy this file to .env and fill in your credentials

# ===== REDDIT CONFIGURATION =====
# Get these from: https://www.reddit.com/prefs/apps
REDDIT_CLIENT_ID=3eHt-T6gVvKZoz0JaukA-A
REDDIT_CLIENT_SECRET=RHg0RGuo1IibamKOZ-gPWoTKn-BO3A
REDDIT_USER_AGENT=bookmarker/1.0 by your_username

# ===== TWITTER CONFIGURATION =====
# Your Twitter username and optional password for automated login
TWITTER_USERNAME=cryptoniard
    TWITTER_PASSWORD="dauren22" # Optional, but helps with login

    # --- Threads Credentials ---
    THREADS_USERNAME="qronoya"
    THREADS_PASSWORD="D@uren22"

# ===== AI ANALYSIS =====
# Professional AI services - the system will try them in order:

# Option 1: Mistral AI (Free tier + professional) - https://console.mistral.ai/
MISTRAL_API_KEY=jfmHTvExCm5uqjbh3L5He6PQiJ6nguEA

# Option 2: Google Gemini (Backup)
GEMINI_API_KEY=AIzaSyCyDv9OpW5rBL2mUvKMfJIKf_8nG_ZWeic

# ===== DEEP RESEARCH (OPTIONAL) =====
# Enhanced pipeline for high-value content research

# Perplexity AI (Best for research) - https://www.perplexity.ai/settings/api
PERPLEXITY_API_KEY=your_perplexity_api_key_here

# ===== OUTPUT SETTINGS =====
OUTPUT_DIRECTORY=./output
OBSIDIAN_MODE=true
OBSIDIAN_VAULT_PATH=/path/to/your/obsidian/vault

# ===== OPTIONAL TELEGRAM (NOT YET IMPLEMENTED) =====
# TELEGRAM_API_ID=your_telegram_api_id
# TELEGRAM_API_HASH=your_telegram_api_hash
# TELEGRAM_PHONE_NUMBER=+1234567890 
# ===== SUPABASE CONFIGURATION =====
SUPABASE_URL=https://drnlmwmigwpfpifeodmm.supabase.co
SUPABASE_SERVICE_ROLE_KEY=sb_secret_SSm7zirMO2yRB4q6TArgMw_95NBTssD
SUPABASE_PAT=sbp_4a10d2784af206358f17c9df44c1ccef671aa2ee
