-- Consolidated Schema Migration - Apply to Supabase
-- =================================================
-- This migration consolidates all schema changes into one file
-- Run this in Supabase SQL Editor after cleaning up existing conflicts
-- =================================================

-- SET statement to avoid issues with existing columns
SET statement_timeout = 60000;

-- 1. CORE POST TABLE STRUCTURE
-- ===========================

-- Basic post fields
ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ADD COLUMN IF NOT EXISTS post_id TEXT UNIQUE NOT NULL,
ADD COLUMN IF NOT EXISTS platform TEXT NOT NULL,
ADD COLUMN IF NOT EXISTS content TEXT,
ADD COLUMN IF NOT EXISTS title TEXT,
ADD COLUMN IF NOT EXISTS author TEXT,
ADD COLUMN IF NOT EXISTS url TEXT,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS collected_at TIMESTAMPTZ DEFAULT NOW();

-- 2. ANALYSIS FIELDS
-- =================

-- Basic analysis fields
ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS analyzed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS analysis_model TEXT,
ADD COLUMN IF NOT EXISTS analysis_version TEXT DEFAULT '1.0',
ADD COLUMN IF NOT EXISTS ai_summary TEXT,
ADD COLUMN IF NOT EXISTS content_summary TEXT,
ADD COLUMN IF NOT EXISTS summary TEXT,
ADD COLUMN IF NOT EXISTS value_score NUMERIC CHECK (value_score >= 0 AND value_score <= 10),
ADD COLUMN IF NOT EXISTS quality_score NUMERIC CHECK (quality_score >= 0 AND quality_score <= 10),
ADD COLUMN IF NOT EXISTS intelligent_value_score NUMERIC CHECK (intelligent_value_score >= 0 AND intelligent_value_score <= 10),
ADD COLUMN IF NOT EXISTS content_quality_score NUMERIC CHECK (content_quality_score >= 0 AND content_quality_score <= 10),
ADD COLUMN IF NOT EXISTS confidence_score NUMERIC CHECK (confidence_score >= 0 AND confidence_score <= 1),
ADD COLUMN IF NOT EXISTS complexity_level TEXT CHECK (complexity_level IN ('beginner', 'intermediate', 'advanced', 'expert')),
ADD COLUMN IF NOT EXISTS time_to_consume INTEGER CHECK (time_to_consume > 0),
ADD COLUMN IF NOT EXISTS sentiment_analysis TEXT,
ADD COLUMN IF NOT EXISTS sentiment_scores JSONB,
ADD COLUMN IF NOT EXISTS ai_service_used TEXT,
ADD COLUMN IF NOT EXISTS ai_service TEXT;

-- Content classification
ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS tags TEXT[],
ADD COLUMN IF NOT EXISTS key_concepts TEXT[],
ADD COLUMN IF NOT EXISTS suggested_tags TEXT[],
ADD COLUMN IF NOT EXISTS topic TEXT,
ADD COLUMN IF NOT EXISTS topics TEXT[],
ADD COLUMN IF NOT EXISTS content_type TEXT,
ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en',
ADD COLUMN IF NOT EXISTS category TEXT,
ADD COLUMN IF NOT EXISTS embedding VECTOR(1536),
ADD COLUMN IF NOT EXISTS embedding_model TEXT;

-- Intelligence analysis
ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS insights TEXT,
ADD COLUMN IF NOT EXISTS recommendations TEXT,
ADD COLUMN IF NOT EXISTS educational_value TEXT,
ADD COLUMN IF NOT EXISTS intelligence_analysis TEXT,
ADD COLUMN IF NOT EXISTS actionable_insights TEXT,
ADD COLUMN IF NOT EXISTS action_items TEXT,
ADD COLUMN IF NOT EXISTS actionable_items TEXT,
ADD COLUMN IF NOT EXISTS learning_value TEXT,
ADD COLUMN IF NOT EXISTS practical_applications TEXT,
ADD COLUMN IF NOT EXISTS related_skills TEXT[],
ADD COLUMN IF NOT EXISTS follow_up_research TEXT,
ADD COLUMN IF NOT EXISTS learning_recommendations TEXT,
ADD COLUMN IF NOT EXISTS quality_indicators TEXT,
ADD COLUMN IF NOT EXISTS why_valuable TEXT;

-- 3. REWRITE FIELDS
-- ================

ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS rewrite_score NUMERIC CHECK (rewrite_score >= 0 AND rewrite_score <= 10),
ADD COLUMN IF NOT EXISTS rewrite_readiness TEXT CHECK (rewrite_readiness IN ('ready', 'needs_research', 'complex', 'not_suitable')),
ADD COLUMN IF NOT EXISTS rewrite_reasons TEXT[],
ADD COLUMN IF NOT EXISTS rewrite_risks TEXT[],
ADD COLUMN IF NOT EXISTS rewrite_angles TEXT[],
ADD COLUMN IF NOT EXISTS rewrite_status TEXT DEFAULT 'not_started',
ADD COLUMN IF NOT EXISTS rewritten_content TEXT,
ADD COLUMN IF NOT EXISTS rewrite_notes TEXT,
ADD COLUMN IF NOT EXISTS is_rewrite_candidate BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS analysis_confidence NUMERIC CHECK (analysis_confidence >= 0 AND analysis_confidence <= 1),
ADD COLUMN IF NOT EXISTS analysis_depth TEXT CHECK (analysis_depth IN ('basic', 'standard', 'deep', 'comprehensive')),
ADD COLUMN IF NOT EXISTS needs_deep_analysis BOOLEAN DEFAULT FALSE;

-- 4. PERSONA FIELDS
-- ================

ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS persona_fit_scores JSONB,
ADD COLUMN IF NOT EXISTS persona_fit_reasons JSONB,
ADD COLUMN IF NOT EXISTS best_persona_key TEXT,
ADD COLUMN IF NOT EXISTS best_persona_score NUMERIC CHECK (best_persona_score >= 0 AND best_persona_score <= 10),
ADD COLUMN IF NOT EXISTS best_persona_reasons TEXT[];

-- 5. ENGAGEMENT & METRICS
-- ======================

ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS engagement JSONB,
ADD COLUMN IF NOT EXISTS performance_metrics JSONB,
ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS posting_platform TEXT,
ADD COLUMN IF NOT EXISTS posting_result JSONB,
ADD COLUMN IF NOT EXISTS time_sensitivity_score NUMERIC CHECK (time_sensitivity_score >= 0 AND time_sensitivity_score <= 10),
ADD COLUMN IF NOT EXISTS expiry_date TIMESTAMPTZ;

-- 6. PUBLISHING FIELDS
-- ===================

ALTER TABLE public.posts
ADD COLUMN IF NOT EXISTS scheduling_priority NUMERIC CHECK (scheduling_priority >= 0 AND scheduling_priority <= 10),
ADD COLUMN IF NOT EXISTS is_scheduled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS is_usable BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS usability_reasons TEXT[],
ADD COLUMN IF NOT EXISTS curation_notes TEXT,
ADD COLUMN IF NOT EXISTS curator_notes TEXT;

-- 7. CONSTRAINTS AND VALIDATIONS
-- =============================

-- Ensure platform is valid
ALTER TABLE public.posts ADD CONSTRAINT IF NOT EXISTS check_platform
CHECK (platform IN ('twitter', 'reddit', 'threads', 'manual'));

-- Ensure content is not null for new posts
ALTER TABLE public.posts ALTER COLUMN content SET NOT NULL;

-- 8. INDEXES FOR PERFORMANCE
-- =========================

-- Core indexes
CREATE INDEX IF NOT EXISTS idx_posts_platform ON public.posts (platform);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_collected_at ON public.posts (collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_updated_at ON public.posts (updated_at DESC);

-- Analysis indexes
CREATE INDEX IF NOT EXISTS idx_posts_analyzed_at ON public.posts (analyzed_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_value_score ON public.posts (value_score DESC);
CREATE INDEX IF NOT EXISTS idx_posts_quality_score ON public.posts (quality_score DESC);
CREATE INDEX IF NOT EXISTS idx_posts_is_rewrite_candidate ON public.posts (is_rewrite_candidate);

-- Rewrite indexes
CREATE INDEX IF NOT EXISTS idx_posts_rewrite_score ON public.posts (rewrite_score DESC);
CREATE INDEX IF NOT EXISTS idx_posts_rewrite_readiness ON public.posts (rewrite_readiness);
CREATE INDEX IF NOT EXISTS idx_posts_rewrite_status ON public.posts (rewrite_status);

-- Content indexes
CREATE INDEX IF NOT EXISTS idx_posts_tags ON public.posts USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_posts_topics ON public.posts USING GIN (topics);
CREATE INDEX IF NOT EXISTS idx_posts_key_concepts ON public.posts USING GIN (key_concepts);

-- Persona indexes
CREATE INDEX IF NOT EXISTS idx_posts_best_persona_score ON public.posts (best_persona_score DESC);

-- Publishing indexes
CREATE INDEX IF NOT EXISTS idx_posts_is_usable ON public.posts (is_usable);
CREATE INDEX IF NOT EXISTS idx_posts_scheduled_for ON public.posts (scheduled_for);
CREATE INDEX IF NOT EXISTS idx_posts_is_scheduled ON public.posts (is_scheduled);

-- 9. TRIGGERS FOR AUTO-UPDATES
-- ===========================

-- Update updated_at on content change
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER IF NOT EXISTS update_posts_updated_at
BEFORE UPDATE ON public.posts
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 10. VIEWS FOR COMMON QUERIES
-- ============================

-- High-quality posts ready for rewriting
CREATE OR REPLACE VIEW vw_rewrite_candidates AS
SELECT *
FROM public.posts
WHERE is_rewrite_candidate = TRUE
  AND value_score >= 7.0
  AND quality_score >= 7.0
  AND rewrite_readiness IN ('ready', 'needs_research')
ORDER BY rewrite_score DESC, best_persona_score DESC;

-- Analyzed posts by persona
CREATE OR REPLACE VIEW vw_persona_fits AS
SELECT
    p.*,
    p.persona_fit_scores->'cryptoniard' as cryptoniard_fit,
    p.persona_fit_scores->'qroniya' as qroniya_fit,
    p.persona_fit_scores->'gptist' as gptist_fit
FROM public.posts p
WHERE p.best_persona_score >= 7.0
ORDER BY p.best_persona_score DESC;

-- Recent unanalyzed posts
CREATE OR REPLACE VIEW vw_unanalyzed_posts AS
SELECT *
FROM public.posts
WHERE analyzed_at IS NULL
ORDER BY collected_at DESC;

-- Usable posts for scheduling
CREATE OR REPLACE VIEW vw_usable_posts AS
SELECT *
FROM public.posts
WHERE is_usable = TRUE
  AND value_score >= 6.0
  AND quality_score >= 6.0
ORDER BY scheduling_priority DESC, collected_at DESC;

-- 11. VERIFICATION QUERIES
-- =======================

-- Check total columns in posts table
SELECT COUNT(*) as total_columns
FROM information_schema.columns
WHERE table_name = 'posts' AND table_schema = 'public';

-- Verify key columns exist
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'posts' AND table_schema = 'public'
  AND column_name IN (
    'id', 'post_id', 'platform', 'content', 'created_at', 'analyzed_at',
    'value_score', 'quality_score', 'rewrite_score', 'rewrite_readiness',
    'best_persona_score', 'is_rewrite_candidate', 'is_usable', 'tags'
  )
ORDER BY column_name;

-- Check indexes were created
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'posts' AND schemaname = 'public'
ORDER BY indexname;

-- 12. CLEANUP NOTES
-- ================
/*
After running this migration:

1. Update application code to use the new standardized column names
2. Remove deprecated migration files:
   - 2025_11_04_final_schema.sql
   - supabase_schema_update.sql
   - Any other overlapping migration files

3. Test the following operations:
   - Inserting new posts
   - Updating post analysis
   - Querying by different scores and filters
   - Using the new views for common operations

4. Update any existing data migration scripts to use the new schema
*/
