-- Add rewrite_angles column to posts table
-- Stores pre-computed creative rewrite angles generated by Gemini
-- Structure: {"qronoya": [{"angle_name": "...", "description": "...", "tone": "...", "approach": "...", "confidence": 0.85}, ...]}

ALTER TABLE posts
ADD COLUMN IF NOT EXISTS rewrite_angles JSONB;

-- Add index for faster queries on rewrite_angles
CREATE INDEX IF NOT EXISTS idx_posts_rewrite_angles ON posts USING GIN (rewrite_angles);

-- Add comment
COMMENT ON COLUMN posts.rewrite_angles IS 'Pre-computed creative rewrite angles per persona, generated by Gemini during curation. Structure: {"persona_key": [angle1, angle2, angle3]}';
