[secrets]
# ✅ CONFIGURED - Your Supabase Database
SUPABASE_URL = "https://drnlmwmigwpfpifeodmm.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybmxtd21pZ3dwZnBpZmVvZG1tIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyMzQ2NzMwMiwiZXhwIjoyMDM5MDQzMzAyfQ.sb_secret_SSm7zirMO2yRB4q6TArgMw_95NBTssD"

# ✅ CONFIGURED - Your AI Services  
MISTRAL_API_KEY = "jfmHTvExCm5uqjbh3L5He6PQiJ6nguEA"
GEMINI_API_KEY = "AIzaSyCyDv9OpW5rBL2mUvKMfJIKf_8nG_ZWeic"

# ✅ CONFIGURED - Your Reddit API
REDDIT_CLIENT_ID = "3eHt-T6gVvKZoz0JaukA-A"
REDDIT_CLIENT_SECRET = "RHg0RGuo1IibamKOZ-gPWoTKn-BO3A"
REDDIT_USER_AGENT = "bookmarker/1.0 by your_username"

# ✅ CONFIGURED - Your Social Media Accounts
TWITTER_USERNAME = "cryptoniard"
TWITTER_PASSWORD = "dauren22"
THREADS_USERNAME = "qronoya"  
THREADS_PASSWORD = "D@uren22"

# Optional - Add if needed
PERPLEXITY_API_KEY = "your_perplexity_api_key_here"
