#!/bin/bash
# Setup script for MCP Supabase server authentication
# This script helps configure the MCP Supabase server with your Personal Access Token

set -e

echo "🔧 MCP Supabase Server Setup"
echo "============================"
echo ""

# Check if token is already set
ENV_FILE="$HOME/.config/supabase-mcp/.env"
if [ -f "$ENV_FILE" ]; then
    if grep -q "SUPABASE_ACCESS_TOKEN=" "$ENV_FILE" && ! grep -q "SUPABASE_ACCESS_TOKEN=$" "$ENV_FILE"; then
        echo "✅ MCP Supabase configuration file exists"
        echo "📝 Current configuration:"
        grep "SUPABASE_ACCESS_TOKEN" "$ENV_FILE" | sed 's/=.*/=***HIDDEN***/'
        echo ""
        read -p "Do you want to update the token? (y/n) " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Keeping existing configuration."
            exit 0
        fi
    fi
fi

echo "📋 To get your Supabase Personal Access Token:"
echo "   1. Go to: https://supabase.com/dashboard/account/tokens"
echo "   2. Click 'Generate new token'"
echo "   3. Give it a name (e.g., 'MCP Server Token')"
echo "   4. Copy the token"
echo ""
read -p "Paste your Supabase Personal Access Token: " -s TOKEN
echo ""

if [ -z "$TOKEN" ]; then
    echo "❌ Error: Token cannot be empty"
    exit 1
fi

# Create directory if it doesn't exist
mkdir -p "$HOME/.config/supabase-mcp"

# Write configuration
cat > "$ENV_FILE" <<EOF
# Supabase MCP Server Configuration
# Generated by setup_mcp_supabase.sh
# Get your token from: https://supabase.com/dashboard/account/tokens
SUPABASE_ACCESS_TOKEN=$TOKEN
EOF

# Set secure permissions
chmod 600 "$ENV_FILE"

echo ""
echo "✅ Configuration saved to: $ENV_FILE"
echo ""
echo "📝 Next steps:"
echo "   1. Restart Cursor completely (Cmd+Q and reopen)"
echo "   2. The MCP Supabase server should now be authenticated"
echo ""
echo "🧪 To test, try running:"
echo "   mcp_supabase_list_projects()"
echo ""






